apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    name: redis
    app: voting-app-pod

spec:
  ports:
  - port: 6379
    targetPort: 6379

  selector:
    name: redis-app
    app: demo-voting-app
